apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangodeployments.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
    - arangodb
    - arango
    singular: arangodeployment
  scope: Namespaced
  version: v1alpha


---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arangodeploymentreplications.replication.database.arangodb.com
spec:
  group: replication.database.arangodb.com
  names:
    kind: ArangoDeploymentReplication
    listKind: ArangoDeploymentReplicationList
    plural: arangodeploymentreplications
    shortNames:
    - arangorepl
    singular: arangodeploymentreplication
  scope: Namespaced
  version: v1alpha