kind: Service
apiVersion: v1
metadata:
  name: kafka-broker
  namespace: kafka-connect-arangodb-dev
spec:
  selector:
    app: kafka-broker
  ports:
  - name: broker
    port: 9092
  - name: broker-host
    port: 29092
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-broker-headless
  namespace: kafka-connect-arangodb-dev
spec:
  selector:
    app: kafka-broker
  clusterIP: None
  ports:
  - name: broker
    port: 9092
  - name: broker-host
    port: 29092