# remove once, operator deletes the pdb when cleanup
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: post-upgrade, post-install
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    type: zookeeper
  name: zookeeper
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      type: zookeeper