apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    labels:
      component: zookeeper
    annotations:
      storageclass.beta.kubernetes.io/is-default-class: "false"
    name: zookeeper-standard-ssd-myzones
  parameters:
    {}
  provisioner:
  reclaimPolicy: Delete
kind: List

