kind: Service
apiVersion: v1
metadata:
  name: zookeeper
  namespace: kafka-connect-arangodb-dev
spec:
  selector:
    app: zookeeper
  ports:
  - name: client
    port: 2181
---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper-headless
  namespace: kafka-connect-arangodb-dev
spec:
  selector:
    app: zookeeper
  clusterIP: None
  ports:
  - name: server
    port: 2888
  - name: leader-election
    port: 3888