apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kafkaconnect
spec:
  version: 2.3.0
  replicas: 2
  image: jaredpetersen/kafka-connect-arangodb:1.0.4
  bootstrapServers: cluster-kafka-bootstrap:9093
