apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 2
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 2
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}