apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-control-center
  namespace: kafka-connect-arangodb-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-control-center
  template:
    metadata:
      labels:
        app: kafka-control-center
    spec:
      containers:
      - name: kafka-control-center
        image: confluentinc/cp-enterprise-control-center:5.2.1
        ports:
        - name: http
          containerPort: 9021
        env:
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "3"
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: kafka-broker-headless:29092
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        # - name: CONTROL_CENTER_CONNECT_CLUSTER
        #   value:
        # CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:${BROKER_PORT}
        # CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
        # CONTROL_CENTER_CONNECT_CLUSTER: connect:${CONNECT_PORT}
        # CONTROL_CENTER_REPLICATION_FACTOR: 1
        # CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
        # CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
        # CONFLUENT_METRICS_TOPIC_REPLICATION: 1
        # PORT: ${CONTROL_CENTER_PORT}
